### ISSUE TITLE
Rendering? Issues

### ISSUE THREAD

**Issue by sotakaneko0808** [Lunatrius/Laser-Level#5]
So now when I open my world, this happens. Please help, it's annoying.

![2016-04-13_16 40 08](https://cloud.githubusercontent.com/assets/18286078/14486290/f5569058-0196-11e6-9635-782b435e2e49.png)

**Comment by Lunatrius** [comment]
Can you test this without any other mods installed?

**Comment by sotakaneko0808** [comment]
Here... It did nothing....

![2016-04-14_05 27 42](https://cloud.githubusercontent.com/assets/18286078/14508278/ad7c5f90-0201-11e6-8717-fe342a3dceb3.png)

**Comment by Lunatrius** [comment]
That's fairly... odd. Does the same thing happen even if you move the marker? Have you tried to create a brand new world to verify that it's not something in the world itself possibly affecting the markers?

**Comment by sotakaneko0808** [comment]
I tried deleting the marker, and this:
![2016-04-14_18 49 13](https://cloud.githubusercontent.com/assets/18286078/14524436/4fe525ca-0273-11e6-88a2-4e5f70a42717.png)
and this:
![2016-04-14_18 49 42](https://cloud.githubusercontent.com/assets/18286078/14524443/5bde90f0-0273-11e6-903e-7f053fdf3da2.png)

happened.
In a new world the same thing happened.
![2016-04-14_18 58 04](https://cloud.githubusercontent.com/assets/18286078/14524478/847fabd4-0273-11e6-96bb-110b4deafe84.png)
![2016-04-14_18 58 13](https://cloud.githubusercontent.com/assets/18286078/14524482/88c0036a-0273-11e6-831e-e6254af1062e.png)

**Comment by Lunatrius** [comment]
Do you have a dedicated NVIDIA or AMD/ATI video card or is the Intel HD 5500 the only one? Something appears to mess with the buffer that stores the markers...

Also could you check and verify whether the same thing happens on the 1.9 version (use Forge **1816 or earlier**)?

**Comment by sotakaneko0808** [comment]
I am too poor to afford a laptop with dedicated graphics... _cries poorly_
I'll comeback with an answer about the 1.9 in a minute....

**Comment by sotakaneko0808** [comment]
![2016-04-14_22 19 08](https://cloud.githubusercontent.com/assets/18286078/14530483/2c29ba26-0294-11e6-9d41-9cbc3fab887b.png)
Same thing on 1.9

**Comment by Lunatrius** [comment]
Could you try turning off VBOs to see if that helps? Trying to find something that would narrow down the possibilities because I can't reproduce it.

**Comment by sotakaneko0808** [comment]
Turning VBOs did help! Thank you! But I kind of need that extra 15~20% faster renders.... Is it possible you can fix it?

**Comment by Lunatrius** [comment]
This might be an issue with Intel HD graphics cards, I'll look into it and what might be causing is.

**Comment by sotakaneko0808** [comment]
Thanks

**Comment by Lunatrius** [comment]
I have switched to my `Intel HD 4000 (ver: 4.0.0 - Build 10.18.10.3345)` and tried a lot of possible graphic related settings (other than unlimited FPS, fast graphics, fast clouds and vbos) - I was unable to reproduce the bug.

The weird thing is that on the 5th and 6th image (new world screenshots) it _partially_ works fine on the first image, while the second one doesn't. Do the markers just flash and it happened to be two different frames or did you change anything in between those 2 screenshots?

From what I can tell, it's trying to render the quads and renders the first triangle but not the second, resulting in that weird zig-zag pattern.

Have you tried to update the Intel drivers? It _might_ fix the issue. Wouldn't be the first nor last driver related issue.

**Comment by Deckee** [comment]
I am having similar issues using a dedicated graphics card [amd 290x], with and without video buffer objects on, and fast and fancy graphics on, the only way to fix this issue for a little bit is to restart the client.

![2016-05-03_01 32 16](https://cloud.githubusercontent.com/assets/8199121/14976179/08582c1a-10cf-11e6-930f-4583c4152555.png)

![2016-05-03_01 33 49](https://cloud.githubusercontent.com/assets/8199121/14976190/2dff176c-10cf-11e6-9984-31efa141e0cb.png)

**Comment by Lunatrius** [comment]
That pretty much puts me back to square one, as I have no idea what your two setups could possibly have in common...

**Comment by Lunatrius** [comment]
Can (finally) reproduce it on 1.9.4. I'll fix it as soon as I can.

**Comment by Lunatrius** [comment]
I'm sorry that this took this long to fix. I'm not sure why the issue wasn't reproducible in 1.9 and earlier versions, but this should **not** have worked, at all.
