### ISSUE TITLE
Overlay renders with a different/pale color

### ISSUE THREAD

**Issue by Lunatrius** [Lunatrius/Laser-Level#6]
Moving the issues from https://github.com/TheCBProject/NotEnoughItems/issues/28 to here.

**Comment by Lunatrius** [comment]
@AlHollandiyah could you upload the screenshots of what it looks like now, after the change was made? And seeing how neither of the 2 possible fixes actually fixed the issue, could you test it with Laser Level and NEI only?

**Comment by ghost** [comment]
Screenshots from new version, now much less transparent, still turning grey at F9:

![2016-10-16_22 36 54](https://cloud.githubusercontent.com/assets/9619351/19420697/2b7048cc-93f1-11e6-9ed1-4ddd80b16901.png)
![2016-10-16_22 37 05](https://cloud.githubusercontent.com/assets/9619351/19420696/2b56c74e-93f1-11e6-89c4-83652255d218.png)

**Comment by ghost** [comment]
@Lunatrius Going to test it right away with only NEI and LL. You do know that NEI recquires JEI as of current, do you? So that will be included in this test also!

**Comment by Lunatrius** [comment]
Uhh... it renders like that because I'm stupid and deleted the wrong list after I was done testing. And yes, any dependencies should obviously be included.

Do you happen to be on EsperNet IRC?

**Comment by ghost** [comment]
Tested with only current mods:

NEI Package (Needs all 4 of listed files, or MC won't load):
- CodeChickenCore v2.3.4.89
- CodeChickenLib v2.4.2.106
- JEI v3.12.7.312
- NotEnoughItems v2.1.2.157

Laser Levels:
- LunatriusCore v1.1.2.36
- LaserLevel v2.1.0.14

Still happens. I will log in to espernet, what channel?
